'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],P=Perf;
const BRANDS=['Cellina Cambodia','Cellina Charm Baby','ULC Modern','Lolane Beauty Shop'];
const PLATFORMS=['Facebook','TikTok','YouTube'];
const state={batches:[],demo:false,filter:{brand:'all',platform:'all',kind:'all',period:'all'},notes:{findings:'',actions:'',decisions:''}};
let pending=null,activeTab='import',busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=0)=>n===null||!Number.isFinite(n)?'—':n.toLocaleString('en-US',{maximumFractionDigits:d});
const pct=n=>n===null?'—':fmt(n,2)+'%';
const uid=()=>crypto.randomUUID();
const option=(arr,value)=>arr.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`}).join('');
function message(text,error=false){$('#notice').textContent=text;$('#notice').classList.toggle('error',error);}
function tab(name){activeTab=name;$$('.tab').forEach(t=>t.classList.toggle('active',t.id===name));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='dashboard')renderDashboard();if(name==='meeting')renderReport();window.scrollTo({top:0,behavior:'smooth'});}
function bindTabs(){$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));}
function selectedBatches(){const f=state.filter;return state.batches.filter(b=>(f.brand==='all'||b.brand===f.brand)&&(f.platform==='all'||b.platform===f.platform)&&(f.kind==='all'||b.kind===f.kind)&&(f.period==='all'||b.start+'|'+b.end===f.period));}
function flat(batches=selectedBatches()){return batches.flatMap(b=>b.rows.map(r=>({...r,brand:b.brand,platform:b.platform,kind:b.kind,grain:b.grain,period:b.start+' → '+b.end,currency:b.currency,source:b.filename})));}
function setBusy(v){busy=v;$('#dropzone').classList.toggle('busy',v);$('#file').disabled=v;}
async function readFile(file){if(!file)return;if(busy)return;try{if(file.size>15*1024*1024)throw Error('File ធំជាង 15 MB។ សូម Export ទិន្នន័យជាចំណែកតូច។');const extension=file.name.split('.').pop().toLowerCase();if(!['xlsx','csv','tsv'].includes(extension))throw Error('សូមប្រើ .xlsx, .csv ឬ .tsv។');setBusy(true);message('កំពុងអាន '+file.name+'…');let sheets={};if(extension==='xlsx'){if(!window.ExcelJS)throw Error('Excel reader មិនទាន់ផ្ទុក។ សូម Reload ទំព័រ។');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());wb.eachSheet(s=>{const rows=[];if(s.columnCount>200||s.rowCount>30001)throw Error('Sheet ធំពេក។ សូម Export អតិបរមា 30,000 ជួរ និង 200 Columns។');s.eachRow({includeEmpty:true},r=>{const a=[];for(let c=1;c<=s.columnCount;c++){const v=r.getCell(c).value;a.push(v instanceof Date?v.toISOString().slice(0,10):v&&typeof v==='object'?('result'in v?v.result:'text'in v?v.text:'richText'in v?v.richText.map(x=>x.text).join(''):''):v??'');}rows.push(a);});sheets[s.name]=rows;});}else{const bytes=await file.arrayBuffer();const u=new Uint8Array(bytes);const encoding=u[0]===255&&u[1]===254?'utf-16le':u[0]===254&&u[1]===255?'utf-16be':'utf-8';sheets['CSV']=P.parseCSV(new TextDecoder(encoding).decode(bytes));}
 if(!Object.keys(sheets).length)throw Error('មិនឃើញ Sheet ដែលមានទិន្នន័យ។');if(Object.values(sheets).some(r=>r.length>30001))throw Error('សូមនាំចូលអតិបរមា 30,000 ជួរក្នុងមួយ Sheet។');pending={filename:file.name,sheets,sheet:Object.keys(sheets)[0],header:0,platform:/tiktok/i.test(file.name)?'TikTok':/youtube/i.test(file.name)?'YouTube':'Facebook',brand:BRANDS[0],kind:'Organic',grain:'content',start:'',end:'',currency:'USD',locale:'us'};autoHeader();renderWizard();message('ជ្រើសកាលបរិច្ឆេទនៃ Report និងផ្គូផ្គងជួរឈរ មុនចុចនាំចូល។');}catch(e){message(e.message||'អាន File មិនបាន។',true);}finally{setBusy(false);$('#file').value='';}}
function autoHeader(){let best=-1,index=0;pending.sheets[pending.sheet].slice(0,30).forEach((row,i)=>{const score=Object.values(P.suggest(row)).filter(n=>n>=0).length;if(score>best){best=score;index=i;}});pending.header=index;pending.map=P.suggest(pending.sheets[pending.sheet][index]||[]);}
function prepare(){const rows=pending.sheets[pending.sheet];return P.normalizeRows(rows.slice(pending.header+1),pending.map,{grain:pending.grain,locale:pending.locale,header:pending.header});}
function renderWizard(){const w=$('#wizard');w.hidden=false;w.className='wizard';const h=pending.sheets[pending.sheet][pending.header]||[];const n=prepare();w.innerHTML=`<div class="panel-head"><h2>${esc(pending.filename)}</h2><button class="secondary" id="cancelImport">បោះបង់</button></div><p class="note">រយៈពេលខាងក្រោមគឺរយៈពេលដែលបានជ្រើសពេល Export។ Publish date មិនមែនជារយៈពេលវាស់លទ្ធផលទេ។</p><div class="form-grid">
${selectInput('sheet','Sheet',Object.keys(pending.sheets))}<label>ជួរឈ្មោះ Column (Header row)<input id="headerRow" type="number" min="1" max="${pending.sheets[pending.sheet].length}" value="${pending.header+1}"></label>${selectInput('platform','Platform',PLATFORMS)}${selectInput('brand','ម៉ាក / Page',BRANDS)}${selectInput('kind','ប្រភពទិន្នន័យ',['Organic','Paid','Total'])}${selectInput('grain','មួយជួរតំណាងឱ្យ',[['content','Post / Video / Ad'],['daily','ទិន្នន័យមួយថ្ងៃ'],['summary','សរុបរយៈពេល (១ ជួរ)']])}<label>ចាប់ពីថ្ងៃ<input type="date" id="start" value="${pending.start}"></label><label>ដល់ថ្ងៃ<input type="date" id="end" value="${pending.end}"></label>${selectInput('currency','រូបិយប័ណ្ណ Spend',['USD','KHR'])}${selectInput('locale','ទម្រង់លេខ',[['us','1,234.56'],['eu','1.234,56']])}</div><h3 style="margin-top:24px">ផ្គូផ្គងជួរឈរ</h3><p class="muted">ពិនិត្យឈ្មោះដែលផ្គូផ្គងស្វ័យប្រវត្តិ។ ជ្រើស «មិនមាន» បើជួរឈរមានន័យខុសគ្នា។</p><div class="mapping">${Object.keys(P.fields).map(k=>`<label>${P.labels[k]}<select data-map="${k}">${option([[-1,'— មិនមាន —'],...h.map((v,i)=>[i,String(v||'Column '+(i+1))])],pending.map[k])}</select></label>`).join('')}</div><p class="note">Engagements ប្រើជួរឈរដែលផ្គូផ្គង។ បើគ្មាន នឹងបូក Likes + Comments + Shares តែនៅពេលមានទាំង ៣។ Followers ជាចំនួនកើនតាម Report មិនមែន Total followers។ Clicks និង Views ត្រូវមាននិយមន័យដូចគ្នាពេលប្រៀបធៀប។</p><div id="validation"></div><div class="table-wrap preview"><table><thead><tr>${h.slice(0,7).map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${pending.sheets[pending.sheet].slice(pending.header+1,pending.header+4).map(r=>`<tr>${h.slice(0,7).map((_,i)=>`<td>${esc(r[i])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="actions" style="margin-top:20px"><button class="primary" id="confirmImport">នាំចូល និងគណនា →</button><span class="muted">File ដើមមិនត្រូវបានកែប្រែ</span></div>`;
 $('#cancelImport').onclick=()=>{pending=null;w.hidden=true;};$('#sheet').onchange=e=>{pending.sheet=e.target.value;autoHeader();renderWizard();};$('#headerRow').onchange=e=>{pending.header=Math.min(pending.sheets[pending.sheet].length-1,Math.max(0,Number(e.target.value)-1));pending.map=P.suggest(pending.sheets[pending.sheet][pending.header]||[]);renderWizard();};
 for(const key of ['platform','brand','kind','grain','start','end','currency','locale'])$('#'+key).onchange=e=>{pending[key]=e.target.value;renderValidation();};$$('[data-map]').forEach(s=>s.onchange=()=>{pending.map[s.dataset.map]=+s.value;renderValidation();});$('#confirmImport').onclick=commitImport;renderValidation();}
function selectInput(key,label,choices){return `<label>${label}<select id="${key}">${option(choices,pending[key])}</select></label>`;}
function renderValidation(){const n=prepare();const used=Object.values(pending.map).filter(v=>v>=0);const repeat=used.length!==new Set(used).size;$('#validation').innerHTML=`<p class="note">${n.rows.length} ជួរអាចនាំចូល · រំលងសរុប ${n.totals} · ស្ទួន ${n.duplicates} · ទទេ/គ្មានលេខ ${n.blanks}</p>${repeat?'<p class="negative">Column តែមួយត្រូវបានផ្គូផ្គងច្រើន Metric។ សូមកែ។</p>':''}${n.errors.length?`<p class="negative">${n.errors.length} បញ្ហា៖ ${n.errors.slice(0,4).map(esc).join(' / ')}</p>`:''}`;$('#confirmImport').disabled=repeat||!!n.errors.length||!n.rows.length;}
function commitImport(){try{if(!P.validDate(pending.start)||!P.validDate(pending.end)||pending.start>pending.end)throw Error('សូមកំណត់ថ្ងៃចាប់ផ្ដើម និងថ្ងៃបញ្ចប់ឱ្យត្រឹមត្រូវ។');const n=prepare();if(n.errors.length||!n.rows.length)throw Error('សូមកែបញ្ហាទិន្នន័យជាមុន។');if(pending.grain==='summary'&&n.rows.length!==1)throw Error('Report សរុបត្រូវមាន ១ ជួរ។ ជ្រើស Sheet សរុប ឬប្រើ Post/Video/ទិន្នន័យមួយថ្ងៃ។');if(pending.grain==='daily'&&pending.map.date<0)throw Error('ទិន្នន័យប្រចាំថ្ងៃត្រូវផ្គូផ្គង Date។');if(pending.grain==='content'&&pending.map.id<0&&pending.map.title<0)throw Error('សូមផ្គូផ្គង Post ID ឬ Title សម្រាប់ Content Report។');
 if(state.demo){if(!confirm('ដកទិន្នន័យគំរូចេញ ហើយប្រើ Report ពិតនេះ?'))return;state.batches=[];state.demo=false;}
 const conflict=state.batches.find(b=>P.overlaps(b,pending));if(conflict)throw Error('រយៈពេលជាន់គ្នាជាមួយ '+conflict.filename+'។ សូមលុប Report ចាស់ ឬប្រើរយៈពេលមិនជាន់គ្នា។');
 const b={id:uid(),filename:pending.filename,sheet:pending.sheet,platform:pending.platform,brand:pending.brand,kind:pending.kind,grain:pending.grain,start:pending.start,end:pending.end,currency:pending.currency,rows:n.rows,mapping:{...pending.map},skipped:{totals:n.totals,duplicates:n.duplicates,blanks:n.blanks}};state.batches.push(b);state.filter.period=b.start+'|'+b.end;pending=null;$('#wizard').hidden=true;refresh();message('នាំចូល '+n.rows.length+' ជួររួច។ ចូល Performance ដើម្បីមើលលទ្ធផល។');}catch(e){message(e.message,true);}}
function refresh(){renderBatches();$('#demoFlag').hidden=!state.demo;$('#dataCount').textContent=state.batches.length+' reports';if(activeTab==='dashboard')renderDashboard();if(activeTab==='meeting')renderReport();}
function renderBatches(){$('#batchCount').textContent=state.batches.length;$('#batchList').innerHTML=state.batches.length?state.batches.map(b=>`<div class="batch"><div><b>${esc(b.filename)}</b><p>${esc(b.platform)} · ${esc(b.brand)} · ${esc(b.kind)} · ${b.rows.length} ជួរ</p><p>${esc(b.start)} → ${esc(b.end)} · ${esc(b.currency)}</p></div><button class="danger" data-remove="${b.id}">លុប</button></div>`).join(''):'<div class="empty"><b>ចាប់ផ្ដើមជាមួយ Report មួយ</b>បងអាចបន្ថែម Platform ផ្សេងៗ បន្ទាប់ពីពិនិត្យ File ដំបូង។</div>';$$('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('លុប Report នេះពីការគណនា?')){state.batches=state.batches.filter(x=>x.id!==b.dataset.remove);state.filter.period='all';refresh();}});}
function renderFilters(){const f=state.filter;const brands=[...new Set(state.batches.map(b=>b.brand))],periods=[...new Set(state.batches.map(b=>b.start+'|'+b.end))].sort().reverse();$('#filters').innerHTML=`<div class="filters">${[['brand','ម៉ាក',[['all','ម៉ាកទាំងអស់'],...brands]],['platform','Platform',[['all','Platform ទាំងអស់'],...PLATFORMS]],['kind','ប្រភព',[['all','ប្រភពទាំងអស់'],'Organic','Paid','Total']],['period','រយៈពេល Report',[['all','រយៈពេលទាំងអស់'],...periods.map(p=>[p,p.replace('|',' → ')])]]].map(([k,l,a])=>`<label>${l}<select data-filter="${k}">${option(a,f[k])}</select></label>`).join('')}</div>`;$$('[data-filter]').forEach(el=>el.onchange=()=>{state.filter[el.dataset.filter]=el.value;renderDashboard();});}
function kpiCards(rows){const a=P.aggregate(rows);return `<div class="kpis">${[['views','Video views'],['impressions','Impressions'],['engagements','Engagements'],['leads','Leads / Inbox']].map(([k,l])=>`<div class="kpi"><span>${l}</span><strong>${fmt(a[k].value)}</strong><small>${a[k].known}/${a[k].count} ជួរមានទិន្នន័យ${a[k].known<a[k].count?' · សរុបមិនពេញ':''}</small></div>`).join('')}</div>`;}
function platformTable(rows){return `<div class="table-wrap"><table><thead><tr><th>Platform</th><th class="num">Views</th><th class="num">Impressions</th><th class="num">Engagements</th><th class="num">CTR</th><th class="num">ER / Impressions</th><th class="num">Watch hours</th><th class="num">Followers / Subs</th></tr></thead><tbody>${PLATFORMS.map(p=>{const rr=rows.filter(r=>r.platform===p),a=P.aggregate(rr);return `<tr><td><b>${p}</b><br><small>${rr.length} ជួរ</small></td>${['views','impressions','engagements'].map(k=>`<td class="num">${fmt(a[k].value)}${a[k].known<a[k].count&&a[k].known?' *':''}</td>`).join('')}<td class="num">${pct(a.ctr)}</td><td class="num">${pct(a.er)}</td><td class="num">${fmt(a.watchHours.value,2)}</td><td class="num">${fmt(a.followers.value)}</td></tr>`;}).join('')}</tbody></table></div>`;}
function insights(rows){const lines=[];for(const p of PLATFORMS){const r=rows.filter(x=>x.platform===p);if(!r.length)continue;const a=P.aggregate(r);lines.push(`${p}: ${fmt(a.views.value)} Views, ${fmt(a.engagements.value)} Engagements និង ${fmt(a.leads.value)} Leads ក្នុង ${r.length} ជួរ។`);}
 const missing=rows.filter(r=>r.views===null).length;if(missing)lines.push(`${missing} ជួរគ្មាន Views។ សរុប Views គ្របដណ្ដប់តែជួរដែលមានលេខ។`);
 if(rows.some(r=>r.kind==='Total'))lines.push('មាន Report Total ដែលអាចរួម Organic និង Paid។ កុំប្រៀបធៀបជាមួយ Organic ដោយផ្ទាល់។');
 if(!lines.length)lines.push('នាំចូល Report ដើម្បីបង្កើតសេចក្ដីសង្ខេប។');return lines;}
function topTable(rows){const content=rows.filter(r=>r.grain==='content'&&Number.isFinite(r.views)).sort((a,b)=>b.views-a.views).slice(0,5);return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Content</th><th>Platform / Source</th><th class="num">Views</th><th class="num">Engagements</th><th class="num">Leads</th></tr></thead><tbody>${content.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.title||r.id)}<br><small>${esc(r.brand)}</small></td><td>${esc(r.platform)} · ${esc(r.kind)}<br><small>${esc(r.period)}</small></td><td class="num">${fmt(r.views)}</td><td class="num">${fmt(r.engagements)}</td><td class="num">${fmt(r.leads)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">ត្រូវការ Content Report ដែលមាន Views ដើម្បីចាត់ថ្នាក់។</td></tr>'}</tbody></table></div>`;}
function paidTable(rows){const groups=[];for(const p of PLATFORMS)for(const c of ['USD','KHR']){const rr=rows.filter(r=>r.platform===p&&r.currency===c&&r.kind==='Paid');if(rr.length)groups.push({p,c,rr,a:P.aggregate(rr)});}return `<div class="table-wrap"><table><thead><tr><th>Paid Platform</th><th>Currency</th><th class="num">Spend</th><th class="num">CPM</th><th class="num">CPC</th><th class="num">CPL</th></tr></thead><tbody>${groups.map(({p,c,rr,a})=>`<tr><td>${p}</td><td>${c}</td><td class="num">${fmt(a.spend.value,2)}</td><td class="num">${fmt(a.cpm,2)}</td><td class="num">${fmt(a.cpc,2)}</td><td class="num">${fmt(a.cpl,2)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">គ្មាន Paid Report ក្នុងជម្រើសនេះ។</td></tr>'}</tbody></table></div>`;}
function renderDashboard(){renderFilters();const rows=flat();if(!rows.length){$('#performance').innerHTML='<div class="panel empty"><b>មិនទាន់មានលេខក្នុងជម្រើសនេះ</b>នាំចូល Report ឬប្ដូរតម្រង។</div>';return;}const vals=PLATFORMS.map(p=>P.total(rows.filter(r=>r.platform===p),'views').value),max=Math.max(1,...vals.filter(n=>n!==null));$('#performance').innerHTML=kpiCards(rows)+`<div class="two-col"><div class="panel"><div class="panel-head"><h2>Views តាម Platform</h2></div><div class="panel-body">${PLATFORMS.map((p,i)=>`<div class="bar-row"><span>${p}</span><div class="bar-track"><i style="width:${(vals[i]||0)/max*100}%"></i></div><strong>${fmt(vals[i])}</strong></div>`).join('')}<p class="footnote">Views របស់ Platform នីមួយៗអាចមាននិយមន័យខុសគ្នា។ មិនមែន Unique audience ទេ។</p></div></div><div class="panel"><div class="panel-head"><h2>ចំណុចសម្រាប់ពិភាក្សា</h2></div><div class="panel-body"><ul class="insights">${insights(rows).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></div><div class="panel"><div class="panel-head"><h2>Platform performance</h2><span class="tag">${rows.length} ជួរ</span></div>${platformTable(rows)}<p class="caption">* សរុបមិនពេញ។ CTR/ER គណនាពីសរុបលេខគូដែលមានគ្រប់ជួរ។ មិនបូក Reach ជា Unique audience ទេ។</p></div><div class="panel" style="margin-top:22px"><div class="panel-head"><h2>Top 5 Content តាម Views</h2></div>${topTable(rows)}<p class="caption">ចំណាត់ថ្នាក់តាម Views តែប៉ុណ្ណោះ។ ប្រើតម្រង Platform និង Organic/Paid ដើម្បីប្រៀបធៀបក្នុងបរិបទដូចគ្នា។</p></div><div class="panel" style="margin-top:22px"><div class="panel-head"><h2>Paid performance</h2></div>${paidTable(rows)}<p class="caption">USD និង KHR គណនាដាច់ពីគ្នា។ «—» = គ្មានលេខគ្រប់គ្រាន់ ឬ denominator សូន្យ។</p></div>`;}
function reportLabel(){const f=state.filter;return [f.brand==='all'?'ម៉ាកទាំងអស់':f.brand,f.platform==='all'?'Platform ទាំងអស់':f.platform,f.kind==='all'?'ប្រភពទាំងអស់':f.kind,f.period==='all'?'រយៈពេលទាំងអស់':f.period.replace('|',' → ')].join(' · ');}
function renderReport(){const rows=flat();$('#excelExport').disabled=$('#print').disabled=!rows.length;if(!rows.length){$('#report').innerHTML='<div class="panel empty"><b>នាំចូល Report ជាមុន</b>របាយការណ៍ប្រជុំនឹងបង្ហាញលទ្ធផលពិតដែលបានជ្រើស។</div>';return;}
 $('#report').innerHTML=`<article class="report-page"><div class="report-heading"><div><span class="eyebrow">SOCIAL MEDIA PERFORMANCE ${state.demo?' / DEMO':''}</span><h2>${esc($('#meetingTitle').value||'Marketing Performance')}</h2><small>${esc(reportLabel())}</small></div><div><small>រៀបចំដោយ: ${esc($('#preparedBy').value||'—')}</small><small>ថ្ងៃរៀបចំ: ${new Date().toISOString().slice(0,10)}</small><small>${selectedBatches().length} Reports · ${rows.length} ជួរ</small></div></div>${kpiCards(rows)}<div class="report-section"><h3>01. សេចក្ដីសង្ខេប</h3><ul>${insights(rows).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="report-section"><h3>02. លទ្ធផលតាម Platform</h3>${platformTable(rows)}</div><div class="report-section"><h3>03. Top Content តាម Views</h3>${topTable(rows)}</div><div class="report-section"><h3>04. Paid performance</h3>${paidTable(rows)}</div><div class="report-section"><h3>05. ការពិភាក្សា និងសកម្មភាពបន្ទាប់</h3><div class="report-notes">${[['findings','អ្វីដែលបានរៀន / បញ្ហាត្រូវដោះស្រាយ'],['actions','សកម្មភាពបន្ទាប់ + អ្នកទទួលខុសត្រូវ + កាលកំណត់'],['decisions','សេចក្ដីសម្រេចក្នុងការប្រជុំ']].map(([k,l])=>`<label>${l}<textarea data-note="${k}" placeholder="បំពេញតាមការវិភាគ និងការពិភាក្សារបស់ក្រុម…">${esc(state.notes[k])}</textarea><div class="print-text" id="print-${k}">${esc(state.notes[k]||'មិនទាន់កត់ត្រា')}</div></label>`).join('')}</div></div><div class="report-section"><h3>06. ប្រភព និងកំណត់សម្គាល់</h3><ul>${selectedBatches().map(b=>`<li>${esc(b.filename)} / ${esc(b.sheet)} · ${esc(b.brand)} · ${esc(b.platform)} ${esc(b.kind)} · ${esc(b.start)}–${esc(b.end)} · ${b.rows.length} ជួរ</li>`).join('')}</ul><p class="footnote">CTR = Clicks ÷ Impressions × 100។ ER = Engagements ÷ Impressions × 100។ CPC = Spend ÷ Clicks។ CPM = Spend ÷ Impressions × 1,000។ CPL = Spend ÷ Leads។ «—» = ទិន្នន័យមិនគ្រប់ ឬ denominator សូន្យ។ * = សរុបមិនពេញ។ Reach មិនត្រូវបានបូកជា Unique audience។ Followers/Subscribers តាមនិយមន័យ Column ដែលបាននាំចូល។ Views មិនមាននិយមន័យដូចគ្នាគ្រប់ Platform។</p></div></article>`;
 $$('[data-note]').forEach(t=>t.oninput=()=>{state.notes[t.dataset.note]=t.value;$('#print-'+t.dataset.note).textContent=t.value||'មិនទាន់កត់ត្រា';});}
function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function saveWorkbook(wb,name){const bytes=await wb.xlsx.writeBuffer();download(name,new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));}
function styleSheet(s){s.views=[{state:'frozen',ySplit:1}];s.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'},size:11};s.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF172A50'}};s.getRow(1).height=30;s.autoFilter={from:{row:1,column:1},to:{row:s.rowCount,column:s.columnCount}};s.columns.forEach((c,i)=>{c.width=i===0?30:22;c.eachCell((cell,row)=>{cell.alignment={vertical:'top',wrapText:true};if(row>1){cell.font={name:'Arial',size:11};if(typeof cell.value==='number')cell.numFmt='#,##0.00';}});});s.pageSetup={paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0};}
async function exportExcel(){try{const rows=flat(),batches=selectedBatches();if(!rows.length)return;const wb=new ExcelJS.Workbook();wb.creator='Marketing Team';const s=wb.addWorksheet('Performance');s.addRow(['Platform','Views','Impressions','Engagements','Clicks','Leads','CTR','ER impressions','Watch hours','Followers or Subs']);PLATFORMS.forEach(p=>{const a=P.aggregate(rows.filter(r=>r.platform===p));s.addRow([p,a.views.value,a.impressions.value,a.engagements.value,a.clicks.value,a.leads.value,a.ctr===null?null:a.ctr/100,a.er===null?null:a.er/100,a.watchHours.value,a.followers.value]);});styleSheet(s);s.getColumn(7).numFmt='0.00%';s.getColumn(8).numFmt='0.00%';
 const paid=wb.addWorksheet('Paid performance');paid.addRow(['Platform','Currency','Spend','CPM','CPC','CPL']);for(const p of PLATFORMS)for(const c of ['USD','KHR']){const rr=rows.filter(r=>r.platform===p&&r.currency===c&&r.kind==='Paid');if(rr.length){const a=P.aggregate(rr);paid.addRow([p,c,a.spend.value,a.cpm,a.cpc,a.cpl]);}}styleSheet(paid);
 const top=wb.addWorksheet('Top content');top.addRow(['Rank','Title','Platform','Brand','Source','Views','Engagements','Leads']);rows.filter(r=>r.grain==='content'&&r.views!==null).sort((a,b)=>b.views-a.views).slice(0,5).forEach((r,i)=>top.addRow([i+1,r.title||r.id,r.platform,r.brand,r.kind,r.views,r.engagements,r.leads]));styleSheet(top);top.getColumn(2).width=50;
 const detail=wb.addWorksheet('Imported data');const keys=['platform','brand','kind','period','source','sourceRow','id','title',...P.metrics];detail.addRow(keys);rows.forEach(r=>detail.addRow(keys.map(k=>r[k]??null)));styleSheet(detail);detail.getColumn(8).width=50;
 const report=wb.addWorksheet('Meeting notes');report.addRow(['Section','Details']);report.addRow(['Title',$('#meetingTitle').value]);report.addRow(['Prepared by',$('#preparedBy').value]);report.addRow(['Selection',reportLabel()]);report.addRow(['Data status',state.demo?'DEMO / SAMPLE':'Imported user reports']);insights(rows).forEach(x=>report.addRow(['Summary',x]));for(const [k,l]of [['findings','Findings'],['actions','Actions / Owner / Deadline'],['decisions','Decisions']])report.addRow([l,state.notes[k]||'មិនទាន់កត់ត្រា']);report.addRow(['Definitions','CTR = Clicks / Impressions; ER = Engagements / Impressions; CPM = Spend / Impressions * 1000; CPC = Spend / Clicks; CPL = Spend / Leads. Missing inputs or zero denominator = blank.']);report.addRow(['Coverage','Totals sum available values only. Missing values are blank, not zero. Check Coverage sheet. Reach is not aggregated. Views and followers definitions depend on mapped source columns.']);styleSheet(report);report.getColumn(2).width=95;for(let i=2;i<=report.rowCount;i++)report.getRow(i).height=52;
 const cov=wb.addWorksheet('Coverage');cov.addRow(['Platform','Metric','Rows with value','Total rows']);PLATFORMS.forEach(p=>{const a=P.aggregate(rows.filter(r=>r.platform===p));P.metrics.forEach(k=>cov.addRow([p,k,a[k].known,a[k].count]));});styleSheet(cov);
 const sources=wb.addWorksheet('Sources');sources.addRow(['File','Sheet','Platform','Brand','Type','Start','End','Rows','Currency','Grain']);batches.forEach(b=>sources.addRow([b.filename,b.sheet,b.platform,b.brand,b.kind,b.start,b.end,b.rows.length,b.currency,b.grain]));styleSheet(sources);await saveWorkbook(wb,'Social-Performance-Report.xlsx');message('ទាញយករបាយការណ៍ Excel រួច។');}catch(e){message('បង្កើត Excel មិនបាន៖ '+e.message,true);}}
async function template(){try{const wb=new ExcelJS.Workbook();for(const p of PLATFORMS){const s=wb.addWorksheet(p);s.addRow(['Post ID','Title','Date','Views','Impressions','Reach','Engagements','Likes','Comments','Shares','Link clicks','Spend','Leads','Net followers','Watch time (hours)']);styleSheet(s);}const help=wb.addWorksheet('Instructions');help.addRows([['Field','Instructions'],['Usage','Paste actual exported data into the platform sheet. Do not enter made-up numbers.'],['Blank values','Leave unavailable metrics blank. Zero means measured zero.'],['Report period','Choose the measurement start/end dates in the website. Publish date is not the reporting period.'],['Engagements','Map source engagements or leave blank to derive Likes + Comments + Shares when all three exist.'],['Followers','Enter net growth for the reporting period, not total followers.'],['Import','Select one sheet, confirm column mapping, brand, Organic/Paid/Total, currency and grain.']]);styleSheet(help);help.getColumn(2).width=100;await saveWorkbook(wb,'Social-Report-Import-Template.xlsx');}catch(e){message(e.message,true);}}
function sample(){if(state.batches.length&&!confirm('ទិន្នន័យគំរូនឹងជំនួសការគណនាបច្ចុប្បន្ន។ បានទាញ Backup ហើយឬនៅ?'))return;state.batches=PLATFORMS.map((p,i)=>({id:uid(),filename:'DEMO-'+p+'.xlsx',sheet:p,platform:p,brand:'Cellina Cambodia',kind:'Organic',grain:'content',start:'2026-08-01',end:'2026-08-31',currency:'USD',rows:[0,1,2].map(j=>{const r={id:'demo-'+i+j,title:['Cleansing Foam · Routine','Body Wash · Fragrance','Shampoo · Product Story'][j],sourceRow:j+2,date:'2026-08-'+String(10+j).padStart(2,'0')};P.metrics.forEach(k=>r[k]=null);Object.assign(r,{views:[18400,31200,9600][j]*(i+1),impressions:50000*(i+1),engagements:300*(j+1),likes:200*(j+1),comments:50*(j+1),shares:50*(j+1),clicks:100*(j+1),leads:10*(j+1),followers:20*(j+1)});return r;})}));state.demo=true;state.filter={brand:'all',platform:'all',kind:'all',period:'all'};refresh();tab('dashboard');message('កំពុងបង្ហាញទិន្នន័យគំរូ។');}
$('#file').onchange=e=>readFile(e.target.files[0]);const dz=$('#dropzone');dz.ondragover=e=>{e.preventDefault();dz.classList.add('drag');};dz.ondragleave=()=>dz.classList.remove('drag');dz.ondrop=e=>{e.preventDefault();dz.classList.remove('drag');if(e.dataTransfer.files.length>1){message('សូមនាំចូលមួយ File ម្ដង ដើម្បីពិនិត្យ Mapping។',true);return;}readFile(e.dataTransfer.files[0]);};
$('#sample').onclick=sample;$('#template').onclick=template;$('#excelExport').onclick=exportExcel;$('#print').onclick=()=>{renderReport();window.print();};$('#meetingTitle').oninput=$('#preparedBy').oninput=()=>{if(activeTab==='meeting')renderReport();};
$('#backup').onclick=()=>download('Social-Performance-Backup.json',new Blob([JSON.stringify({version:1,...state,title:$('#meetingTitle').value,preparedBy:$('#preparedBy').value},null,2)],{type:'application/json'}));
$('#restore').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>30*1024*1024)throw Error('Backup ធំជាង 30 MB។');const p=JSON.parse(await file.text());if(p.version!==1||!Array.isArray(p.batches))throw Error('Backup មិនត្រឹមត្រូវ។');for(const b of p.batches){if(!PLATFORMS.includes(b.platform)||!BRANDS.includes(b.brand)||!['Organic','Paid','Total'].includes(b.kind)||!['USD','KHR'].includes(b.currency)||!['content','daily','summary'].includes(b.grain)||!P.validDate(b.start)||!P.validDate(b.end)||b.start>b.end||!Array.isArray(b.rows)||b.rows.length>30000||typeof b.filename!=='string')throw Error('ទម្រង់ Report ក្នុង Backup មិនត្រឹមត្រូវ។');for(const r of b.rows){if(!r||typeof r!=='object')throw Error('ជួរទិន្នន័យមិនត្រឹមត្រូវ។');for(const k of P.metrics)if(r[k]!==null&&(!Number.isFinite(r[k])||(r[k]<0&&k!=='followers')))throw Error('Metric ក្នុង Backup មិនត្រឹមត្រូវ។');}}
 if(state.batches.length&&!confirm('បើក Backup ហើយជំនួសទិន្នន័យបច្ចុប្បន្ន?'))return;state.batches=p.batches.map(b=>({...b,id:uid()}));state.demo=!!p.demo;state.filter={brand:'all',platform:'all',kind:'all',period:'all'};state.notes={findings:String(p.notes?.findings||''),actions:String(p.notes?.actions||''),decisions:String(p.notes?.decisions||'')};$('#meetingTitle').value=p.title||'Marketing Performance';$('#preparedBy').value=p.preparedBy||'';refresh();message('បើក Backup រួច។');}catch(err){message(err.message,true);}finally{e.target.value='';}};
window.addEventListener('beforeunload',e=>{if(state.batches.length){e.preventDefault();e.returnValue='';}});bindTabs();refresh();
